import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import Link from 'next/link';

export default function Nums(props) {
  const router = useRouter();
  const { num } = router.query; 

  return(
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="main">
        <h1>{`지금은 nums/${num} (동적 라우팅) 페이지 입니다.`}</h1>
        <div>
          <small>동적 라우팅에서 파라미터는 useRouter().query를 용해 받아올 수 있습니다.</small>
        </div>
        <div>
          <Link href="/">
            index 페이지로
          </Link>
        </div>
      </div>
    </div>
  );
}