import Head from 'next/head';
import Link from 'next/link';

export default function Apple(props) {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="main">
        <h1>지금은 apple 페이지 입니다.</h1>
        <Link href="/">
          index 페이지로
        </Link>
      </div>
    </div>
  )
}
