import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import Link from 'next/link';

export default function Index(props) {
  const router = useRouter();

  const num = 1000 + Math.floor(Math.random() * 999);

  const handleClickRouterPush = e => {
    router.push( e.target.getAttribute("data-href") )
  }
  const handleClickRouterReplace = e => {
    router.replace( e.target.getAttribute("data-href") )
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="main">
        <h1>지금은 index 페이지 입니다.</h1>
        <div>
          <Link href="/apple">
            apple 페이지로
          </Link>
        </div>
        <br />
        
        <div>
          <Link href={ "/nums/"+num }>
            {`num/${num} 페이지로`}
          </Link>
        </div>
        <br />

        <div
          onClick={handleClickRouterPush}
          data-href="/apple"
        >
          apple 페이지로 (라우터 객체 push)
        </div>
        <br />

        <div
          onClick={handleClickRouterReplace}
          data-href="/apple"
        >
          apple 페이지로 (라우터 객체 replace)
        </div>
        <br />
        <br />
        <br />
        <br />
        <small>  
          [참고]<br />
          <a href="https://nextjs.org/docs/basic-features/pages" target="_blank" rel="noopener noreferrer">
            ㅇ next.js 공홈 :: pages 디렉터로 컨셉
          </a><br />
          <a href="https://nextjs.org/docs/routing/introduction" target="_blank" rel="noopener noreferrer">
            ㅇ next.js 공홈 :: routing 소개
          </a><br />
        </small>
      </div>
    </div>
  )
}
